MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 0.25
  TRIPLET_LOSS_WEIGHT : 1.0
  I2T_LOSS_WEIGHT : 0.5
  I2Teacher_LOSS_TYPE : 'L2'
  I2Teacher_LOSS_WEIGHT : 0.3
  VISUAL_MODEL : 'clipreid_vit'

  LRP : ''
  # pure CLIP trained prompt parameter
  PRETRAIN_PATH : "/data/keti/syh/checkpoints/CLIP_ReID_pure_Test_on_MSMT17_re/ViT-B-16_stage1_120.pth"
  DINO_TEACHER : True
  DINO_PRETRAIN_PATH : "/data/keti/syh/exp/DINO_MSMT17_train_reid_shape_256_112_ratio_2_1/checkpoint0200.pth"


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROMPT_BASE : "A photo of a X X X X person." # 23.11.13 prompt test for Task-aware

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  STAGE1:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.00035
    WARMUP_LR_INIT: 0.00001
    LR_MIN: 1e-6
    WARMUP_METHOD: 'linear'
    WEIGHT_DECAY:  1e-4
    WEIGHT_DECAY_BIAS: 1e-4
    MAX_EPOCHS: 120
    CHECKPOINT_PERIOD: 120
    LOG_PERIOD: 50
    WARMUP_EPOCHS: 5

  STAGE2:
    IMS_PER_BATCH: 64
    OPTIMIZER_NAME: "Adam"
    BASE_LR: 0.000005
    WARMUP_METHOD: 'linear'
    WARMUP_ITERS: 10
    WARMUP_FACTOR: 0.1
    WEIGHT_DECAY:  0.0001
    WEIGHT_DECAY_BIAS: 0.0001
    LARGE_FC_LR: False
    MAX_EPOCHS: 60
    CHECKPOINT_PERIOD: 5
    LOG_PERIOD: 50
    EVAL_PERIOD: 60
    BIAS_LR_FACTOR: 2

    STEPS: [30, 50]
    GAMMA: 0.1

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  GRADCAM : False
DATASETS:
#   NAMES: ('market1501')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''e

#   NAMES: ('dukemtmc')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

#   NAMES: ('occ_duke')
#   ROOT_DIR: ('')
# OUTPUT_DIR: ''

  NAMES: ('msmt17')
  ROOT_DIR: ('/data/keti/syh/ReID')

OUTPUT_DIR: '/data/keti/syh/checkpoints/CLIP_ReID_MSMT_DINO_Teacher_03'

